### ISSUE TITLE
Can't get logging to work

### ISSUE THREAD

**Issue by johnnyplaydrums** [opsxcq/docker-dnsmasq#1]
Hello! Thank you for this docker image 🙂. I haven't been able to get logging to work, except if I use the `-d` flag, which I don't want to use in production. The `-q` flag should log all queries, but I only see logs with the `-d` flag. Any idea? I'm running the container with:
```
docker run -it -p 53:53/udp -p 53:53/tcp -v $(pwd)/dnsmasq.conf:/etc/dnsmasq.conf --cap-add=NET_ADMIN strm/dnsmasq -q
```

With very simple `dnsmasq.conf`:
```
address=/router/10.1.1.1
```

When I run the container and `dig router` I get a record for 10.1.1.1 in return, so the container is running fine but I'm just see logs. Thanks for the help!

**Comment by Laski** [comment]
@johnnyplaydrums having the same issue. would you mind to share how did you fix it?

**Comment by johnnyplaydrums** [comment]
Hey @Laski, unfortunately I didn't find a fix for this, but if you end up finding one please feel free to share 🙂

**Comment by Laski** [comment]
@johnnyplaydrums 
I did! Just add this lines somewhere in your `dnsmasq.conf`

```
# Log all dns queries to stdout
log-queries
log-facility=-
```
And to avoid filling up your disk with logs add
```
    logging:
        options:
            max-file: "5"
            max-size: "10m"
```
to your `docker-compose.yml` (at the same indentation level than the `image` key).

**Comment by johnnyplaydrums** [comment]
Beautiful, thank you for sharing @Laski!
